on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build, Deploy to Server
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}

#       - name: Transfer to S3 for serving static
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: !!YOUR_BUCKET!!
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#           AWS_REGION: 'us-west-1'
#           SOURCE_DIR: 'website/build/' + !!YOUR_PROJECT!!
